export const countMap = new Map([["Fire Alarm", "alarm_count"], ["Ambulance", "ambulance_count"], ["Party", "party_count"]]);
export const dormMap = new Map([["Ambler Johnston (East)", "east_aj"],
["Ambler Johnston (West)", "west_aj"],
["Campbell (Main)", "main_campbell"],
["Campbell (East)", "east_campbell"],
["Cochrane", "cochrane"],
["The Creativity and Innovation District Residence Hall", "cid"],
["Eggleston (East)", "east_egg"],
["Eggleston (Main)", "main_egg"],
["Eggleston (West)", "west_egg"],
["Graduate Life Center at Donaldson Brown", "glc"],
["Harper", "harper"],
["Hillcrest", "hillcrest"],
["Hoge Hall", "hoge"],
["Johnson", "johnson"],
["Miles", "miles"],
["New Hall West", "west_new_hall"],
["New Residence Hall East", "east_new_hall"],
["Newman", "newman"],
["O'Shaughnessy Hall", "oshag"],
["Payne", "payne"],
["Pearson Hall East", "east_pearson"],
["Pearson Hall West", "west_pearson"],
["Peddrew-Yates", "peddrew_yates"],
["Pritchard", "pritchard"],
["Slusher Hall", "slusher"],
["Upper Quad Hall North", "upper_quad"],
["Vawter", "vawter"],
["Whitehurst Hall", "whitehurst"]]);